name: Integrate EMQX
on:
  push:
    branches:
      - trunk
jobs:
  docker:
    runs-on:
      group: hosted
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build
      run: docker build --file ./deploy/docker/Dockerfile --tag ghcr.io/blabtm/emqx:latest
    -
      name: Push
      run: docker push ghcr.io/blabtm/emqx:latest
