name: Run Configuration tests

concurrency:
  group: conftest-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      builder:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run_conf_tests:
    runs-on: ${{ endsWith(github.repository, '/emqx') && 'ubuntu-22.04' || fromJSON('["self-hosted","ephemeral","linux","x64"]') }}
    container: ${{ inputs.builder }}
    env:
      PROFILE: ${{ matrix.profile }}
    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
          - emqx-enterprise
    steps:
      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: ${{ matrix.profile }}
      - name: extract artifact
        run: |
          unzip -o -q ${{ matrix.profile }}.zip
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: make ${{ matrix.profile }}
      - run: ./scripts/test/check-example-configs.sh
      - run: ./scripts/conf-test/run.sh
      - name: print erlang log
        if: failure()
        run: |
          cat _build/${{ matrix.profile }}/rel/emqx/log/erlang.log.*
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        if: failure()
        with:
          name: conftest-logs-${{ matrix.profile }}
          path: _build/${{ matrix.profile }}/rel/emqx/log
          retention-days: 7
